"""
    Even Fibonacci numbers
Show HTML problem content 
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
"""

def fibonacci_loop(acaba):

	a = 1 
	b = 1
	c = 1

	while c < acaba:
		print(c)
		c = a + b 
		a = b  
		b = c
